import type { AgentConfig } from '../types.js';

/**
 * Generates src/activation/inject-claude-md.ts for a new agent.
 * Provides idempotent CLAUDE.md injection — creates, appends, or updates
 * the agent's section between HTML comment markers.
 * Supports both project-level and global (~/.claude/CLAUDE.md) injection.
 *
 * Uses array-joined pattern because the generated code contains
 * template literals (backticks) for path operations and string interpolation.
 */
export function generateInjectClaudeMd(config: AgentConfig): string {
  const marker = `${config.id}:mode`;

  return [
    "import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';",
    "import { homedir } from 'node:os';",
    "import { join } from 'node:path';",
    "import { getClaudeMdContent, getClaudeMdMarker } from './claude-md-content.js';",
    "",
    "export interface InjectResult {",
    "  injected: boolean;",
    "  path: string;",
    "  action: 'created' | 'updated' | 'appended';",
    "}",
    "",
    "/**",
    " * Inject into a specific CLAUDE.md file path.",
    " * Shared logic for both project-level and global injection.",
    " */",
    "function injectIntoFile(filePath: string): InjectResult {",
    "  const content = getClaudeMdContent();",
    "  const marker = getClaudeMdMarker();",
    `  const startMarker = '<!-- ' + marker + ' -->';`,
    `  const endMarker = '<!-- /' + marker + ' -->';`,
    "",
    "  if (!existsSync(filePath)) {",
    "    writeFileSync(filePath, content + '\\n', 'utf-8');",
    "    return { injected: true, path: filePath, action: 'created' };",
    "  }",
    "",
    "  const existing = readFileSync(filePath, 'utf-8');",
    "",
    "  if (existing.includes(startMarker)) {",
    "    const startIdx = existing.indexOf(startMarker);",
    "    const endIdx = existing.indexOf(endMarker);",
    "    if (endIdx === -1) {",
    "      const updated = existing.slice(0, startIdx) + content + '\\n' + existing.slice(startIdx + startMarker.length);",
    "      writeFileSync(filePath, updated, 'utf-8');",
    "      return { injected: true, path: filePath, action: 'updated' };",
    "    }",
    "    const updated = existing.slice(0, startIdx) + content + existing.slice(endIdx + endMarker.length);",
    "    writeFileSync(filePath, updated, 'utf-8');",
    "    return { injected: true, path: filePath, action: 'updated' };",
    "  }",
    "",
    "  const separator = existing.endsWith('\\n') ? '\\n' : '\\n\\n';",
    "  writeFileSync(filePath, existing + separator + content + '\\n', 'utf-8');",
    "  return { injected: true, path: filePath, action: 'appended' };",
    "}",
    "",
    "/**",
    " * Inject agent CLAUDE.md section into a project.",
    " * - If no CLAUDE.md exists: creates one",
    " * - If markers found: replaces content between them (update)",
    " * - If no markers: appends section to end",
    " */",
    "export function injectClaudeMd(projectPath: string): InjectResult {",
    "  return injectIntoFile(join(projectPath, 'CLAUDE.md'));",
    "}",
    "",
    "/**",
    " * Inject agent CLAUDE.md section into the global ~/.claude/CLAUDE.md.",
    " * Creates ~/.claude/ directory if it doesn't exist.",
    " * This makes the activation phrase work in any project.",
    " */",
    "export function injectClaudeMdGlobal(): InjectResult {",
    "  const claudeDir = join(homedir(), '.claude');",
    "  if (!existsSync(claudeDir)) {",
    "    mkdirSync(claudeDir, { recursive: true });",
    "  }",
    "  return injectIntoFile(join(claudeDir, 'CLAUDE.md'));",
    "}",
    "",
    "/**",
    " * Check if the agent marker exists in a CLAUDE.md file.",
    " */",
    "export function hasAgentMarker(filePath: string): boolean {",
    "  if (!existsSync(filePath)) return false;",
    "  const content = readFileSync(filePath, 'utf-8');",
    `  return content.includes('<!-- ${marker} -->');`,
    "}",
  ].join('\n');
}
