import type { AgentConfig } from '../types.js';

/**
 * Generate the LLM client file for a new agent.
 * Contains LLMClient (OpenAI fetch + Anthropic SDK) and ModelRouter (inlined).
 * Uses config.id to resolve ~/.{agentId}/model-routing.json.
 */
export function generateLLMClient(config: AgentConfig): string {
  return `/**
 * LLM Client — Unified OpenAI/Anthropic caller with key pool rotation
 * Generated by agent-forge — do not edit manually.
 */

import Anthropic from '@anthropic-ai/sdk';
import { SecretString, LLMError } from './types.js';
import type {
  LLMCallOptions,
  LLMCallResult,
  RouteEntry,
  RoutingConfig,
} from './types.js';
import { CircuitBreaker, retry, parseRateLimitHeaders } from './utils.js';
import type { KeyPool } from './key-pool.js';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { homedir } from 'node:os';

// =============================================================================
// CONSTANTS
// =============================================================================

const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';

// =============================================================================
// MODEL ROUTER (inlined)
// =============================================================================

function loadRoutingConfig(): RoutingConfig {
  const defaultConfig: RoutingConfig = {
    routes: [],
    defaultOpenAIModel: 'gpt-4o-mini',
    defaultAnthropicModel: 'claude-sonnet-4-20250514',
  };

  const configPath = path.join(
    homedir(),
    '.${config.id}',
    'model-routing.json',
  );

  try {
    if (fs.existsSync(configPath)) {
      const data = JSON.parse(fs.readFileSync(configPath, 'utf-8')) as Partial<RoutingConfig>;
      if (data.routes && Array.isArray(data.routes)) {
        defaultConfig.routes = data.routes;
      }
      if (data.defaultOpenAIModel) {
        defaultConfig.defaultOpenAIModel = data.defaultOpenAIModel;
      }
      if (data.defaultAnthropicModel) {
        defaultConfig.defaultAnthropicModel = data.defaultAnthropicModel;
      }
    }
  } catch {
    // Config not available — use defaults
  }

  return defaultConfig;
}

function inferProvider(model: string): 'openai' | 'anthropic' {
  if (model.startsWith('claude-') || model.startsWith('anthropic/')) {
    return 'anthropic';
  }
  return 'openai';
}

class ModelRouter {
  private config: RoutingConfig;

  constructor(config?: RoutingConfig) {
    this.config = config || loadRoutingConfig();
  }

  resolve(
    caller: string,
    task?: string,
    originalModel?: string,
  ): { model: string; provider: 'openai' | 'anthropic' } {
    if (task) {
      const exactMatch = this.config.routes.find(
        (r) => r.caller === caller && r.task === task,
      );
      if (exactMatch) {
        return { model: exactMatch.model, provider: exactMatch.provider };
      }
    }

    const callerMatch = this.config.routes.find(
      (r) => r.caller === caller && !r.task,
    );
    if (callerMatch) {
      return { model: callerMatch.model, provider: callerMatch.provider };
    }

    if (originalModel) {
      const provider = inferProvider(originalModel);
      return { model: originalModel, provider };
    }

    return { model: this.config.defaultOpenAIModel, provider: 'openai' };
  }

  getRoutes(): RouteEntry[] {
    return [...this.config.routes];
  }
}

// =============================================================================
// LLM CLIENT
// =============================================================================

export class LLMClient {
  private openaiKeyPool: KeyPool;
  private anthropicKeyPool: KeyPool;
  private anthropicClient: Anthropic | null = null;
  private anthropicBreaker: CircuitBreaker;
  private anthropicKeyFingerprint: string = '';
  private router: ModelRouter;

  constructor(openaiKeyPool: KeyPool, anthropicKeyPool: KeyPool) {
    this.openaiKeyPool = openaiKeyPool;
    this.anthropicKeyPool = anthropicKeyPool;
    this.anthropicBreaker = new CircuitBreaker({
      name: 'llm-anthropic',
      failureThreshold: 5,
      resetTimeoutMs: 60_000,
    });
    this.router = new ModelRouter();
  }

  async complete(options: LLMCallOptions): Promise<LLMCallResult> {
    const routed = this.router.resolve(
      options.caller,
      options.task,
      options.model,
    );
    const resolvedOptions = { ...options, model: routed.model, provider: routed.provider };

    return resolvedOptions.provider === 'anthropic'
      ? this.callAnthropic(resolvedOptions)
      : this.callOpenAI(resolvedOptions);
  }

  isAvailable(): { openai: boolean; anthropic: boolean } {
    return {
      openai: this.openaiKeyPool.hasKeys,
      anthropic: this.anthropicKeyPool.hasKeys,
    };
  }

  getRoutes(): RouteEntry[] {
    return this.router.getRoutes();
  }

  // ===========================================================================
  // OPENAI
  // ===========================================================================

  private async callOpenAI(options: LLMCallOptions): Promise<LLMCallResult> {
    const keyPool = this.openaiKeyPool.hasKeys ? this.openaiKeyPool : null;

    if (!keyPool) {
      throw new LLMError('OpenAI API key not configured', { retryable: false });
    }

    const start = Date.now();

    const doRequest = async (): Promise<LLMCallResult> => {
      const apiKey = keyPool.getActiveKey().expose();
      const keyIndex = keyPool.activeKeyIndex;

      const response = await fetch(OPENAI_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: \`Bearer \${apiKey}\`,
        },
        body: JSON.stringify({
          model: options.model,
          messages: [
            { role: 'system', content: options.systemPrompt },
            { role: 'user', content: options.userPrompt },
          ],
          temperature: options.temperature ?? 0.3,
          max_completion_tokens: options.maxTokens ?? 500,
        }),
      });

      if (response.headers) {
        const rateLimits = parseRateLimitHeaders(response.headers);
        if (rateLimits.remaining !== null) {
          keyPool.updateQuota(keyIndex, rateLimits.remaining);
          keyPool.rotatePreemptive();
        }
      }

      if (!response.ok) {
        if (response.status === 429 && keyPool.poolSize > 1) {
          keyPool.rotateOnError();
        }

        const errorBody = await response.text();
        throw new LLMError(
          \`OpenAI API error: \${response.status} - \${errorBody}\`,
          { retryable: response.status === 429 || response.status >= 500, statusCode: response.status },
        );
      }

      const data = (await response.json()) as {
        choices: Array<{ message: { content: string } }>;
        usage?: { prompt_tokens?: number; completion_tokens?: number };
      };

      return {
        text: data.choices[0]?.message?.content || '',
        model: options.model,
        provider: 'openai' as const,
        inputTokens: data.usage?.prompt_tokens,
        outputTokens: data.usage?.completion_tokens,
        durationMs: Date.now() - start,
      };
    };

    return retry(doRequest, { maxAttempts: 3 });
  }

  // ===========================================================================
  // ANTHROPIC
  // ===========================================================================

  private async callAnthropic(options: LLMCallOptions): Promise<LLMCallResult> {
    const client = this.getAnthropicClient();
    if (!client) {
      throw new LLMError('Anthropic API key not configured', { retryable: false });
    }

    const start = Date.now();

    return this.anthropicBreaker.call(() =>
      retry(
        async () => {
          const response = await client.messages.create(
            {
              model: options.model,
              max_tokens: options.maxTokens ?? 1024,
              system: options.systemPrompt,
              messages: [{ role: 'user', content: options.userPrompt }],
            },
            { timeout: 60_000 },
          );

          const text = response.content
            .filter(
              (block): block is Anthropic.TextBlock => block.type === 'text',
            )
            .map((block) => block.text)
            .join('\\n');

          return {
            text,
            model: options.model,
            provider: 'anthropic' as const,
            inputTokens: response.usage?.input_tokens,
            outputTokens: response.usage?.output_tokens,
            durationMs: Date.now() - start,
          };
        },
        { maxAttempts: 2 },
      ),
    );
  }

  private getAnthropicClient(): Anthropic | null {
    if (!this.anthropicKeyPool.hasKeys) return null;

    const currentKey = this.anthropicKeyPool.getActiveKey().expose();
    const currentFingerprint = currentKey.slice(-8);

    if (currentFingerprint !== this.anthropicKeyFingerprint) {
      this.anthropicClient = null;
      this.anthropicKeyFingerprint = currentFingerprint;
    }

    if (this.anthropicClient) return this.anthropicClient;

    this.anthropicClient = new Anthropic({ apiKey: currentKey });
    return this.anthropicClient;
  }
}
`;
}
