/**
 * Generates src/planning/planner.ts for a new agent.
 * The Planner provides JSON-file-backed plan management with state machine transitions.
 */
export function generatePlanner(): string {
  return PLANNER_TEMPLATE;
}

const PLANNER_TEMPLATE = [
  "import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';",
  "import { dirname } from 'node:path';",
  "",
  "export type PlanStatus = 'draft' | 'approved' | 'executing' | 'completed';",
  "export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'skipped' | 'failed';",
  "",
  "export interface PlanTask {",
  "  id: string;",
  "  title: string;",
  "  description: string;",
  "  status: TaskStatus;",
  "  updatedAt: number;",
  "}",
  "",
  "export interface Plan {",
  "  id: string;",
  "  objective: string;",
  "  scope: string;",
  "  status: PlanStatus;",
  "  decisions: string[];",
  "  tasks: PlanTask[];",
  "  createdAt: number;",
  "  updatedAt: number;",
  "}",
  "",
  "export interface PlanStore {",
  "  version: string;",
  "  plans: Plan[];",
  "}",
  "",
  "export class Planner {",
  "  private filePath: string;",
  "  private store: PlanStore;",
  "",
  "  constructor(filePath: string) {",
  "    this.filePath = filePath;",
  "    this.store = this.load();",
  "  }",
  "",
  "  private load(): PlanStore {",
  "    if (!existsSync(this.filePath)) {",
  "      return { version: '1.0', plans: [] };",
  "    }",
  "    try {",
  "      const data = readFileSync(this.filePath, 'utf-8');",
  "      return JSON.parse(data) as PlanStore;",
  "    } catch {",
  "      return { version: '1.0', plans: [] };",
  "    }",
  "  }",
  "",
  "  private save(): void {",
  "    mkdirSync(dirname(this.filePath), { recursive: true });",
  "    writeFileSync(this.filePath, JSON.stringify(this.store, null, 2), 'utf-8');",
  "  }",
  "",
  "  create(params: { objective: string; scope: string; decisions?: string[]; tasks?: Array<{ title: string; description: string }> }): Plan {",
  "    const now = Date.now();",
  "    const plan: Plan = {",
  "      id: `plan-${now}-${Math.random().toString(36).slice(2, 8)}`,",
  "      objective: params.objective,",
  "      scope: params.scope,",
  "      status: 'draft',",
  "      decisions: params.decisions ?? [],",
  "      tasks: (params.tasks ?? []).map((t, i) => ({",
  "        id: `task-${i + 1}`,",
  "        title: t.title,",
  "        description: t.description,",
  "        status: 'pending' as TaskStatus,",
  "        updatedAt: now,",
  "      })),",
  "      createdAt: now,",
  "      updatedAt: now,",
  "    };",
  "    this.store.plans.push(plan);",
  "    this.save();",
  "    return plan;",
  "  }",
  "",
  "  get(planId: string): Plan | null {",
  "    return this.store.plans.find((p) => p.id === planId) ?? null;",
  "  }",
  "",
  "  list(): Plan[] {",
  "    return [...this.store.plans];",
  "  }",
  "",
  "  approve(planId: string): Plan {",
  "    const plan = this.get(planId);",
  "    if (!plan) throw new Error(`Plan not found: ${planId}`);",
  "    if (plan.status !== 'draft') throw new Error(`Cannot approve plan in '${plan.status}' status — must be 'draft'`);",
  "    plan.status = 'approved';",
  "    plan.updatedAt = Date.now();",
  "    this.save();",
  "    return plan;",
  "  }",
  "",
  "  startExecution(planId: string): Plan {",
  "    const plan = this.get(planId);",
  "    if (!plan) throw new Error(`Plan not found: ${planId}`);",
  "    if (plan.status !== 'approved') throw new Error(`Cannot execute plan in '${plan.status}' status — must be 'approved'`);",
  "    plan.status = 'executing';",
  "    plan.updatedAt = Date.now();",
  "    this.save();",
  "    return plan;",
  "  }",
  "",
  "  updateTask(planId: string, taskId: string, status: TaskStatus): Plan {",
  "    const plan = this.get(planId);",
  "    if (!plan) throw new Error(`Plan not found: ${planId}`);",
  "    if (plan.status !== 'executing') throw new Error(`Cannot update tasks on plan in '${plan.status}' status — must be 'executing'`);",
  "    const task = plan.tasks.find((t) => t.id === taskId);",
  "    if (!task) throw new Error(`Task not found: ${taskId}`);",
  "    task.status = status;",
  "    task.updatedAt = Date.now();",
  "    plan.updatedAt = Date.now();",
  "    // Auto-transition: if plan is executing and first task starts, that's fine",
  "    // Auto-start execution when approving and updating first task",
  "    this.save();",
  "    return plan;",
  "  }",
  "",
  "  complete(planId: string): Plan {",
  "    const plan = this.get(planId);",
  "    if (!plan) throw new Error(`Plan not found: ${planId}`);",
  "    if (plan.status !== 'executing') throw new Error(`Cannot complete plan in '${plan.status}' status — must be 'executing'`);",
  "    plan.status = 'completed';",
  "    plan.updatedAt = Date.now();",
  "    this.save();",
  "    return plan;",
  "  }",
  "",
  "  getExecuting(): Plan[] {",
  "    return this.store.plans.filter((p) => p.status === 'executing');",
  "  }",
  "",
  "  getActive(): Plan[] {",
  "    return this.store.plans.filter((p) => p.status === 'draft' || p.status === 'approved' || p.status === 'executing');",
  "  }",
  "}",
].join('\n');
