/**
 * Generates intelligence loader test file for a new agent.
 * Tests cover: load valid JSON bundles, skip invalid entries, missing dir, malformed JSON.
 */
export function generateLoaderTest(): string {
  return LOADER_TEST_TEMPLATE;
}

const LOADER_TEST_TEMPLATE = [
  "import { describe, it, expect, beforeEach, afterEach } from 'vitest';",
  "import { mkdirSync, rmSync, writeFileSync } from 'node:fs';",
  "import { join } from 'node:path';",
  "import { tmpdir } from 'node:os';",
  "import { loadIntelligenceData } from '../intelligence/loader.js';",
  "",
  "describe('Intelligence Loader', () => {",
  "  let tempDir: string;",
  "",
  "  beforeEach(() => {",
  "    tempDir = join(tmpdir(), `loader-test-${Date.now()}`);",
  "    mkdirSync(tempDir, { recursive: true });",
  "  });",
  "",
  "  afterEach(() => {",
  "    rmSync(tempDir, { recursive: true, force: true });",
  "  });",
  "",
  "  it('should load valid entries from JSON files', () => {",
  "    writeFileSync(join(tempDir, 'test-domain.json'), JSON.stringify({",
  "      domain: 'test-domain',",
  "      version: '1.0.0',",
  "      entries: [",
  "        {",
  "          id: 'entry-1',",
  "          type: 'pattern',",
  "          domain: 'test-domain',",
  "          title: 'Test Pattern',",
  "          severity: 'warning',",
  "          description: 'A test pattern.',",
  "          tags: ['test'],",
  "        },",
  "      ],",
  "    }));",
  "",
  "    const entries = loadIntelligenceData(tempDir);",
  "    expect(entries).toHaveLength(1);",
  "    expect(entries[0].id).toBe('entry-1');",
  "    expect(entries[0].domain).toBe('test-domain');",
  "  });",
  "",
  "  it('should load entries from multiple files', () => {",
  "    for (const domain of ['api', 'db']) {",
  "      writeFileSync(join(tempDir, `${domain}.json`), JSON.stringify({",
  "        domain,",
  "        version: '1.0.0',",
  "        entries: [",
  "          { id: `${domain}-1`, type: 'pattern', domain, title: 'P1', severity: 'warning', description: 'Desc', tags: ['t'] },",
  "          { id: `${domain}-2`, type: 'rule', domain, title: 'R1', severity: 'critical', description: 'Desc', tags: ['t'] },",
  "        ],",
  "      }));",
  "    }",
  "",
  "    const entries = loadIntelligenceData(tempDir);",
  "    expect(entries).toHaveLength(4);",
  "  });",
  "",
  "  it('should skip entries with missing required fields', () => {",
  "    writeFileSync(join(tempDir, 'bad.json'), JSON.stringify({",
  "      domain: 'bad',",
  "      version: '1.0.0',",
  "      entries: [",
  "        { id: '', type: 'pattern', domain: 'bad', title: 'Missing ID', severity: 'warning', description: 'D', tags: ['t'] },",
  "        { id: 'ok-1', type: 'pattern', domain: 'bad', title: 'Valid', severity: 'warning', description: 'D', tags: ['t'] },",
  "        { type: 'pattern', domain: 'bad', title: 'No ID', severity: 'warning', description: 'D', tags: ['t'] },",
  "      ],",
  "    }));",
  "",
  "    const entries = loadIntelligenceData(tempDir);",
  "    expect(entries).toHaveLength(1);",
  "    expect(entries[0].id).toBe('ok-1');",
  "  });",
  "",
  "  it('should skip entries with invalid type', () => {",
  "    writeFileSync(join(tempDir, 'invalid-type.json'), JSON.stringify({",
  "      domain: 'x',",
  "      version: '1.0.0',",
  "      entries: [",
  "        { id: 'bad-type', type: 'unknown', domain: 'x', title: 'T', severity: 'warning', description: 'D', tags: ['t'] },",
  "      ],",
  "    }));",
  "",
  "    const entries = loadIntelligenceData(tempDir);",
  "    expect(entries).toHaveLength(0);",
  "  });",
  "",
  "  it('should accept entries with empty tags', () => {",
  "    writeFileSync(join(tempDir, 'no-tags.json'), JSON.stringify({",
  "      domain: 'x',",
  "      version: '1.0.0',",
  "      entries: [",
  "        { id: 'no-tags', type: 'pattern', domain: 'x', title: 'T', severity: 'warning', description: 'D', tags: [] },",
  "      ],",
  "    }));",
  "",
  "    const entries = loadIntelligenceData(tempDir);",
  "    expect(entries).toHaveLength(1);",
  "    expect(entries[0].tags).toEqual([]);",
  "  });",
  "",
  "  it('should return empty for nonexistent directory', () => {",
  "    const entries = loadIntelligenceData('/nonexistent/path');",
  "    expect(entries).toEqual([]);",
  "  });",
  "",
  "  it('should skip malformed JSON files gracefully', () => {",
  "    writeFileSync(join(tempDir, 'broken.json'), '{ not valid json }}}');",
  "    writeFileSync(join(tempDir, 'valid.json'), JSON.stringify({",
  "      domain: 'good',",
  "      version: '1.0.0',",
  "      entries: [",
  "        { id: 'v1', type: 'rule', domain: 'good', title: 'Good', severity: 'suggestion', description: 'Works', tags: ['ok'] },",
  "      ],",
  "    }));",
  "",
  "    const entries = loadIntelligenceData(tempDir);",
  "    expect(entries).toHaveLength(1);",
  "    expect(entries[0].id).toBe('v1');",
  "  });",
  "",
  "  it('should skip files without entries array', () => {",
  "    writeFileSync(join(tempDir, 'no-entries.json'), JSON.stringify({",
  "      domain: 'incomplete',",
  "      version: '1.0.0',",
  "    }));",
  "",
  "    const entries = loadIntelligenceData(tempDir);",
  "    expect(entries).toEqual([]);",
  "  });",
  "",
  "  it('should ignore non-JSON files', () => {",
  "    writeFileSync(join(tempDir, 'readme.txt'), 'Not a JSON file');",
  "    const entries = loadIntelligenceData(tempDir);",
  "    expect(entries).toEqual([]);",
  "  });",
  "});",
].join('\n');
