import type { AgentConfig } from '../types.js';

/**
 * Generate the LLM key pool file for a new agent.
 * KeyPool manages multiple API keys with per-key circuit breakers.
 * Uses config.id to resolve ~/.{agentId}/keys.json.
 */
export function generateLLMKeyPool(config: AgentConfig): string {
  return `/**
 * Key Pool — Multi-key management with auto-rotation
 * Generated by Soleri — do not edit manually.
 *
 * Key loading priority:
 * 1. ~/.${config.id}/keys.json → { "openai": ["sk-..."], "anthropic": ["sk-ant-..."] }
 * 2. Fallback: OPENAI_API_KEY / ANTHROPIC_API_KEY env vars
 * 3. Empty pool → graceful degradation
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { homedir } from 'node:os';
import { SecretString } from './types.js';
import type { KeyPoolConfig, KeyStatus } from './types.js';
import { CircuitBreaker } from './utils.js';

// =============================================================================
// CONSTANTS
// =============================================================================

const DEFAULT_PREEMPTIVE_THRESHOLD = 50;

// =============================================================================
// KEY POOL
// =============================================================================

class RateLimitRotationError extends Error {
  retryable = true;
  constructor() {
    super('Rate limit rotation');
    this.name = 'RateLimitRotationError';
  }
}

export class KeyPool {
  private keys: SecretString[];
  private activeIndex: number = 0;
  private keyBreakers: Map<number, CircuitBreaker> = new Map();
  private remainingQuota: Map<number, number> = new Map();
  private readonly preemptiveThreshold: number;

  constructor(config: KeyPoolConfig) {
    this.keys = config.keys
      .filter((k) => k.length > 0)
      .map((k) => new SecretString(k));
    this.preemptiveThreshold =
      config.preemptiveThreshold ?? DEFAULT_PREEMPTIVE_THRESHOLD;

    for (let i = 0; i < this.keys.length; i++) {
      this.keyBreakers.set(
        i,
        new CircuitBreaker({
          name: \`key-pool-\${i}\`,
          failureThreshold: 3,
          resetTimeoutMs: 30_000,
        }),
      );
    }

    if (this.keys.length > 1) {
      console.error(\`[LLM] KeyPool initialized with \${this.keys.length} keys\`);
    }
  }

  get hasKeys(): boolean {
    return this.keys.length > 0;
  }

  getActiveKey(): SecretString {
    return this.keys[this.activeIndex];
  }

  get activeKeyIndex(): number {
    return this.activeIndex;
  }

  get poolSize(): number {
    return this.keys.length;
  }

  get exhausted(): boolean {
    if (this.keys.length === 0) return true;
    for (let i = 0; i < this.keys.length; i++) {
      const breaker = this.keyBreakers.get(i)!;
      if (!breaker.isOpen()) return false;
    }
    return true;
  }

  rotateOnError(): SecretString | null {
    const breaker = this.keyBreakers.get(this.activeIndex);
    if (breaker) {
      breaker.recordFailure();
    }
    return this.findNextHealthyKey();
  }

  rotatePreemptive(): boolean {
    const previousIndex = this.activeIndex;
    const remaining = this.remainingQuota.get(previousIndex);
    if (remaining !== undefined && remaining < this.preemptiveThreshold) {
      const next = this.findNextHealthyKey();
      if (next) {
        console.error(
          \`[LLM] KeyPool preemptive rotation: key \${previousIndex} remaining=\${remaining} < threshold=\${this.preemptiveThreshold}\`,
        );
        return true;
      }
    }
    return false;
  }

  updateQuota(keyIndex: number, remaining: number): void {
    this.remainingQuota.set(keyIndex, remaining);
  }

  getStatus(): {
    poolSize: number;
    activeKeyIndex: number;
    exhausted: boolean;
    perKeyStatus: KeyStatus[];
  } {
    const perKeyStatus: KeyStatus[] = [];
    for (let i = 0; i < this.keys.length; i++) {
      perKeyStatus.push({
        index: i,
        circuitState: this.keyBreakers.get(i)!.getState(),
        remainingQuota: this.remainingQuota.get(i) ?? null,
      });
    }
    return {
      poolSize: this.poolSize,
      activeKeyIndex: this.activeIndex,
      exhausted: this.exhausted,
      perKeyStatus,
    };
  }

  private findNextHealthyKey(): SecretString | null {
    const startIndex = this.activeIndex;
    for (let offset = 1; offset <= this.keys.length; offset++) {
      const candidateIndex = (startIndex + offset) % this.keys.length;
      const breaker = this.keyBreakers.get(candidateIndex)!;
      if (!breaker.isOpen()) {
        this.activeIndex = candidateIndex;
        return this.keys[candidateIndex];
      }
    }
    console.error('[LLM] KeyPool: all keys exhausted — no healthy key available');
    return null;
  }
}

// =============================================================================
// KEY LOADING
// =============================================================================

export interface KeyPoolFiles {
  openai: KeyPoolConfig;
  anthropic: KeyPoolConfig;
}

export function loadKeyPoolConfig(): KeyPoolFiles {
  const keysFilePath = path.join(
    homedir(),
    '.${config.id}',
    'keys.json',
  );

  let openaiKeys: string[] = [];
  let anthropicKeys: string[] = [];

  try {
    if (fs.existsSync(keysFilePath)) {
      const data = JSON.parse(fs.readFileSync(keysFilePath, 'utf-8'));
      if (data?.openai && Array.isArray(data.openai)) {
        openaiKeys = data.openai;
      }
      if (data?.anthropic && Array.isArray(data.anthropic)) {
        anthropicKeys = data.anthropic;
      }
    }
  } catch {
    console.error('[LLM] Could not read keys.json, falling back to env vars');
  }

  // Fallback: environment variables
  if (openaiKeys.length === 0) {
    const envKey = process.env.OPENAI_API_KEY || '';
    if (envKey) openaiKeys = [envKey];
  }
  if (anthropicKeys.length === 0) {
    const envKey = process.env.ANTHROPIC_API_KEY || '';
    if (envKey) anthropicKeys = [envKey];
  }

  return {
    openai: { keys: openaiKeys },
    anthropic: { keys: anthropicKeys },
  };
}
`;
}
