/**
 * Generate the LLM utils file for a new agent.
 * Contains CircuitBreaker, retry with backoff+jitter, and rate limit header parser.
 */
export function generateLLMUtils(): string {
  return `/**
 * LLM Utilities — Circuit Breaker, Retry, Rate Limit Parser
 * Generated by Soleri — do not edit manually.
 */

import type {
  CircuitBreakerConfig,
  CircuitBreakerSnapshot,
  CircuitState,
  LLMError,
  RateLimitInfo,
  RetryConfig,
} from './types.js';

// =============================================================================
// HELPERS
// =============================================================================

function isRetryable(error: unknown): boolean {
  if (error && typeof error === 'object' && 'retryable' in error) {
    return (error as { retryable: boolean }).retryable === true;
  }
  return false;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// =============================================================================
// CIRCUIT BREAKER
// =============================================================================

const DEFAULT_CB_CONFIG: CircuitBreakerConfig = {
  failureThreshold: 5,
  resetTimeoutMs: 60_000,
  name: 'default',
};

export class CircuitOpenError extends Error {
  retryable = false;
  constructor(name: string) {
    super(\`\${name} circuit breaker is open — calls are being rejected\`);
    this.name = 'CircuitOpenError';
    Object.setPrototypeOf(this, CircuitOpenError.prototype);
  }
}

export class CircuitBreaker {
  private state: CircuitState = 'closed';
  private failureCount = 0;
  private lastFailureAt: number | null = null;
  private readonly config: CircuitBreakerConfig;

  constructor(config?: Partial<CircuitBreakerConfig>) {
    this.config = { ...DEFAULT_CB_CONFIG, ...config };
  }

  async call<T>(fn: () => Promise<T>): Promise<T> {
    if (this.state === 'open') {
      if (this.shouldProbe()) {
        this.transitionTo('half-open');
      } else {
        throw new CircuitOpenError(this.config.name);
      }
    }

    try {
      const result = await fn();
      this.onSuccess();
      return result;
    } catch (error) {
      this.onFailure(error);
      throw error;
    }
  }

  getState(): CircuitBreakerSnapshot {
    if (this.state === 'open' && this.shouldProbe()) {
      this.transitionTo('half-open');
    }
    return {
      state: this.state,
      failureCount: this.failureCount,
      lastFailureAt: this.lastFailureAt,
    };
  }

  isOpen(): boolean {
    return this.state === 'open' && !this.shouldProbe();
  }

  reset(): void {
    this.transitionTo('closed');
    this.failureCount = 0;
    this.lastFailureAt = null;
  }

  /** Synchronously record a failure (used by KeyPool to trip breaker without async) */
  recordFailure(): void {
    this.failureCount++;
    this.lastFailureAt = Date.now();
    if (this.state === 'half-open') {
      this.transitionTo('open');
      return;
    }
    if (this.failureCount >= this.config.failureThreshold) {
      console.error(\`[LLM] CircuitBreaker:\${this.config.name} threshold reached (\${this.failureCount}/\${this.config.failureThreshold}) — opening\`);
      this.transitionTo('open');
    }
  }

  private onSuccess(): void {
    this.failureCount = 0;
    this.transitionTo('closed');
  }

  private onFailure(error: unknown): void {
    if (!isRetryable(error)) {
      return;
    }

    this.failureCount++;
    this.lastFailureAt = Date.now();

    if (this.state === 'half-open') {
      this.transitionTo('open');
      return;
    }

    if (this.failureCount >= this.config.failureThreshold) {
      console.error(\`[LLM] CircuitBreaker:\${this.config.name} threshold reached (\${this.failureCount}/\${this.config.failureThreshold}) — opening\`);
      this.transitionTo('open');
    }
  }

  private shouldProbe(): boolean {
    if (this.lastFailureAt === null) return false;
    return Date.now() - this.lastFailureAt >= this.config.resetTimeoutMs;
  }

  private transitionTo(newState: CircuitState): void {
    if (this.state !== newState) {
      this.state = newState;
    }
  }
}

// =============================================================================
// RETRY
// =============================================================================

const DEFAULT_RETRY_CONFIG: RetryConfig = {
  maxAttempts: 3,
  baseDelayMs: 1000,
  maxDelayMs: 30000,
  jitter: 0.1,
};

export function computeDelay(
  error: unknown,
  attempt: number,
  config: RetryConfig,
): number {
  const retryAfterMs = (error as Partial<LLMError> & { retryAfterMs?: number })?.retryAfterMs;
  if (retryAfterMs !== undefined && retryAfterMs > 0) {
    return Math.min(retryAfterMs, config.maxDelayMs);
  }

  const exponential = config.baseDelayMs * Math.pow(2, attempt);
  const capped = Math.min(exponential, config.maxDelayMs);

  const jitterRange = capped * config.jitter;
  const jitterOffset = (Math.random() * 2 - 1) * jitterRange;

  return Math.max(0, Math.round(capped + jitterOffset));
}

export async function retry<T>(
  fn: () => Promise<T>,
  config?: Partial<RetryConfig>,
): Promise<T> {
  const resolved: RetryConfig = { ...DEFAULT_RETRY_CONFIG, ...config };
  const shouldRetry = resolved.shouldRetry ?? isRetryable;

  let lastError: unknown;

  for (let attempt = 0; attempt < resolved.maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;

      if (attempt >= resolved.maxAttempts - 1 || !shouldRetry(error)) {
        throw error;
      }

      const delay = computeDelay(error, attempt, resolved);
      resolved.onRetry?.(error, attempt + 1, delay);

      await sleep(delay);
    }
  }

  throw lastError;
}

// =============================================================================
// RATE LIMIT HEADER PARSER
// =============================================================================

export function parseRateLimitHeaders(headers: Headers): RateLimitInfo {
  const remaining = headers.get('x-ratelimit-remaining-requests');
  const reset = headers.get('x-ratelimit-reset-requests');
  const retryAfter = headers.get('retry-after');

  return {
    remaining: remaining !== null ? parseInt(remaining, 10) : null,
    resetMs: reset !== null ? parseResetDuration(reset) : null,
    retryAfterMs: retryAfter !== null ? parseRetryAfter(retryAfter) : null,
  };
}

function parseResetDuration(value: string): number | null {
  let totalMs = 0;
  let matched = false;

  const minMatch = value.match(/(\\d+)m(?!\\s*s)/);
  if (minMatch) {
    totalMs += parseInt(minMatch[1], 10) * 60_000;
    matched = true;
  }

  const msMatch = value.match(/(\\d+)ms/);
  if (msMatch) {
    totalMs += parseInt(msMatch[1], 10);
    matched = true;
  }

  const secMatch = value.match(/(\\d+)(?<!m)s/);
  if (secMatch) {
    totalMs += parseInt(secMatch[1], 10) * 1000;
    matched = true;
  }

  return matched ? totalMs : null;
}

function parseRetryAfter(value: string): number | null {
  const seconds = parseFloat(value);
  return isNaN(seconds) ? null : Math.ceil(seconds * 1000);
}
`;
}
