/**
 * Editor-specific hook/config templates.
 *
 * Each template function reads agent identity and generates
 * editor-appropriate configuration files.
 */
import { detectAgent } from '../utils/agent-context.js';

export type EditorId = 'claude-code' | 'cursor' | 'windsurf' | 'copilot';

export const SUPPORTED_EDITORS: EditorId[] = ['claude-code', 'cursor', 'windsurf', 'copilot'];

interface AgentMeta {
  agentId: string;
  packageName: string;
}

/** Sanitize agent ID for safe interpolation into shell commands and templates. */
function sanitizeId(id: string): string {
  return id.replace(/[^a-z0-9-]/g, '');
}

function getAgentMeta(dir?: string): AgentMeta | null {
  const ctx = detectAgent(dir);
  if (!ctx) return null;
  return { agentId: sanitizeId(ctx.agentId), packageName: ctx.packageName };
}

// ── Claude Code ──

function generateClaudeCodeSettings(dir?: string): Record<string, string> {
  const meta = getAgentMeta(dir);
  const agentId = meta?.agentId ?? 'my-agent';

  const settings = JSON.stringify(
    {
      hooks: {
        PreToolUse: [
          {
            matcher: '*',
            hooks: [
              {
                type: 'command',
                command: `echo "[${agentId}] tool: $TOOL_NAME"`,
              },
            ],
          },
        ],
        PostToolUse: [
          {
            matcher: 'Edit|Write',
            hooks: [
              {
                type: 'command',
                command: `echo "[${agentId}] file changed"`,
              },
            ],
          },
        ],
        SessionStart: [
          {
            hooks: [
              {
                type: 'command',
                command: `echo "[${agentId}] session started"`,
              },
            ],
          },
        ],
      },
    },
    null,
    2,
  );

  return {
    '.claude/settings.json': settings,
  };
}

// ── Cursor ──

function generateCursorRules(dir?: string): Record<string, string> {
  const meta = getAgentMeta(dir);
  const agentId = meta?.agentId ?? 'my-agent';

  const rules = `# ${agentId} — Cursor Rules
# Generated by soleri hooks add cursor

## Agent Context
This project is a Soleri AI agent (${agentId}).
The agent uses the MCP protocol and is structured with facades, a vault, and a brain.

## Key Directories
- src/facades/ — MCP tool facades (one per domain)
- src/intelligence/data/ — Knowledge bundles (JSON)
- src/identity/ — Persona definition
- src/activation/ — Activation and CLAUDE.md injection

## Conventions
- All facades follow the FacadeConfig pattern from @soleri/core
- Knowledge entries use the pattern/anti-pattern/rule taxonomy
- Domain names are kebab-case
- Facade names use the pattern: {agentId}_{domain}
`;

  return {
    '.cursorrules': rules,
  };
}

// ── Windsurf ──

function generateWindsurfRules(dir?: string): Record<string, string> {
  const meta = getAgentMeta(dir);
  const agentId = meta?.agentId ?? 'my-agent';

  const rules = `# ${agentId} — Windsurf Rules
# Generated by soleri hooks add windsurf

## Agent Context
This project is a Soleri AI agent (${agentId}).
The agent uses the MCP protocol and is structured with facades, a vault, and a brain.

## Key Directories
- src/facades/ — MCP tool facades (one per domain)
- src/intelligence/data/ — Knowledge bundles (JSON)
- src/identity/ — Persona definition
- src/activation/ — Activation and CLAUDE.md injection

## Conventions
- All facades follow the FacadeConfig pattern from @soleri/core
- Knowledge entries use the pattern/anti-pattern/rule taxonomy
- Domain names are kebab-case
- Facade names use the pattern: {agentId}_{domain}
`;

  return {
    '.windsurfrules': rules,
  };
}

// ── GitHub Copilot ──

function generateCopilotInstructions(dir?: string): Record<string, string> {
  const meta = getAgentMeta(dir);
  const agentId = meta?.agentId ?? 'my-agent';

  const instructions = `# ${agentId} — Copilot Instructions
<!-- Generated by soleri hooks add copilot -->

## Agent Context
This project is a Soleri AI agent (${agentId}).
The agent uses the MCP protocol and is structured with facades, a vault, and a brain.

## Key Directories
- \`src/facades/\` — MCP tool facades (one per domain)
- \`src/intelligence/data/\` — Knowledge bundles (JSON)
- \`src/identity/\` — Persona definition
- \`src/activation/\` — Activation and CLAUDE.md injection

## Conventions
- All facades follow the FacadeConfig pattern from @soleri/core
- Knowledge entries use the pattern/anti-pattern/rule taxonomy
- Domain names are kebab-case
- Facade names use the pattern: \`{agentId}_{domain}\`
`;

  return {
    '.github/copilot-instructions.md': instructions,
  };
}

export function getEditorFiles(editor: EditorId, dir?: string): Record<string, string> {
  switch (editor) {
    case 'claude-code':
      return generateClaudeCodeSettings(dir);
    case 'cursor':
      return generateCursorRules(dir);
    case 'windsurf':
      return generateWindsurfRules(dir);
    case 'copilot':
      return generateCopilotInstructions(dir);
  }
}
