import type { Locale } from '../types';

export const homeContent = (locale: Locale) => content[locale];

const content: Record<Locale, HomeContent> = {
  en: {
    heroTitle: 'What you <span class="accent-amber">teach</span> it <span class="accent-teal">stays</span>. What it <span class="accent-green">learns</span> compounds.',
    heroText: 'Persistent memory. Structured knowledge. Context that carries across every session.',
    principleTitle: 'Knowledge should compound — not evaporate.',
    compareBeforeLabel: 'Without memory',
    compareAfterLabel: 'With Soleri',
    compareBefore: `<span class="dim">// Session 1</span>
<span class="warn">You:</span> We use Tailwind with semantic tokens,
      never raw hex. Spacing is 4px base.
<span class="warn">AI:</span>  Got it! I'll follow that.

<span class="dim">// Session 2 — next day</span>
<span class="warn">You:</span> Why did you use #3B82F6 again?
<span class="warn">AI:</span>  Sorry, can you remind me of your
      color conventions?

<span class="dim">// Session 47 — same question, again</span>`,
    compareAfter: `<span class="dim">// Session 1</span>
<span class="hl">You:</span> We use Tailwind with semantic tokens.
<span class="hl">AI:</span>  Captured to vault. I'll enforce this.

<span class="dim">// Session 47</span>
<span class="hl">You:</span> Review this component.
<span class="hl">AI:</span>  Found 2 raw hex values. Your vault says
      semantic tokens only. Fixing now.
      <span class="ok">✓ Pattern applied from vault</span>
      <span class="ok">✓ Brain strength: 94% (12 sessions)</span>`,
    howTitle: 'One engine.<br/>One vault.<br/>No coordination overhead.',
    howText: 'A <strong>Vault</strong> for knowledge, a <strong>Brain</strong> that learns, <strong>Memory</strong> that persists. Single process. Feed it knowledge — it organizes, vectorizes, and learns.',
    engineTags: ['Vault', 'Brain', 'Memory'],
    features: [
      {
        title: 'Configuration as code',
        text: 'One command generates the config. Voice, domains, vault backends — all declarative, all version-controlled.',
        code: `<span class="cmt"># agent.yaml (generated by create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">direct, technical, thorough</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastructure]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Pluggable knowledge packs',
        text: 'npm packages you snap into any agent. Starter and community packs ship free.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">built-in</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">installed</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">installed</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">shared vault</span>`,
      },
      {
        title: 'Transport &amp; LLM agnostic',
        text: 'Pure TypeScript core. Protocol adapters are separate files. Swap transports without touching the engine.',
        code: `<span class="key">engine/core/</span>        <span class="cmt"># zero protocol deps</span>
├── vault.ts
├── brain.ts
└── memory.ts
<span class="key">engine/transports/</span>  <span class="cmt"># swap without touching core</span>
├── <span class="ok">mcp.ts</span>         <span class="cmt"># ships now</span>
├── rest.ts        <span class="cmt"># dashboards, APIs</span>
└── lsp.ts         <span class="cmt"># VS Code, Cursor, Zed</span>`,
      },
      {
        title: 'Cold start, not blank slate',
        text: 'Starter knowledge on create. Project scan on first run. Guided capture as you work.',
        code: `<span class="cmt">$ soleri create my-agent</span>
<span class="ok">✓</span> Installed starter knowledge  <span class="val">34 patterns</span>
<span class="ok">✓</span> Scanned project              <span class="val">React + TS</span>
<span class="ok">✓</span> Auto-captured                <span class="val">12 patterns</span>
<span class="ok">✓</span> Vault ready                  <span class="val">46 entries</span>

<span class="cmt"># After 3 sessions:</span>
<span class="warn">Brain:</span> You've fixed this import style 3×.
       <span class="val">Capture as pattern? [y/n]</span>`,
      },
    ],
    cardsTitle: 'One vault. Many domains.',
    cards: [
      { title: 'Frontend', domain: 'Domain', cls: 'salvador', capabilities: ['React patterns', 'Design tokens', 'Component review', 'Accessibility'], ships: 'Ask about buttons — the vault searches here first.' },
      { title: 'Backend', domain: 'Domain', cls: 'gaudi', capabilities: ['API conventions', 'Database schemas', 'Auth patterns', 'Performance'], ships: 'Ask about queries or API design — the vault pulls from here.' },
      { title: 'Cross-cutting', domain: 'Domain', cls: 'sentinel', capabilities: ['Git workflows', 'Code review', 'Testing strategies', 'Documentation'], ships: 'Patterns that span domains. The graph finds connections automatically.' },
    ],
    terminalTitle: 'Terminal',
    terminalCode: `<span class="comment"># Install and create</span>
<span class="prompt">$</span> <span class="cmd">npm install</span> <span class="arg">-g soleri</span>
<span class="prompt">$</span> <span class="cmd">soleri create</span> <span class="arg">my-agent</span>

<span class="comment">  ✓ Created agent config</span>
<span class="comment">  ✓ Connected vault (starter knowledge: 34 patterns)</span>
<span class="comment">  ✓ Scanned project: React + TypeScript</span>
<span class="comment">  ✓ Auto-captured 12 codebase patterns</span>
<span class="comment">  ✓ Vault ready — 46 entries, vectorized, graph-connected</span>

<span class="comment"># Feed it more knowledge</span>
<span class="prompt">$</span> <span class="cmd">soleri packs</span> <span class="arg">install community/react-patterns</span>
<span class="prompt">$</span> <span class="cmd">soleri vault</span> <span class="arg">connect git@github.com:team/vault.git</span>`,
    archTitle: 'Layered like living systems',
    archSubtitle: 'Each layer grows independently. Swap transports, plug in knowledge, customize your agent — the engine stays the same.',
    layers: [
      { label: 'Agents', text: 'Your agent\'s config (<code>agent.yaml</code>): identity, voice, domain wiring. Create in one command, customize anytime.' },
      { label: 'Domains', text: 'Pluggable knowledge domains. The engine loads relevant domains based on your agent\'s vault structure.' },
      { label: 'Engine', text: 'Single MCP server process. Vault (knowledge), Brain (learning), Memory (context), Planning (workflows). Your agent runs on it. Updates via <code>npm update</code>.' },
      { label: 'Transports', text: 'Protocol adapters isolated from core: <code>mcp.ts</code> ships now, <code>rest.ts</code> and <code>lsp.ts</code> ready for VS Code, Cursor, Zed, and custom dashboards. Adding a transport = one adapter file.' },
    ],
  },
  uk: {
    heroTitle: '<span class="accent-amber">Навчиш</span> — <span class="accent-teal">лишиться</span>. <span class="accent-green">Навчиться</span> — примножиться.',
    heroText: 'Постійна пам\'ять. Структуровані знання. Контекст, що зберігається між усіма сесіями.',
    principleTitle: 'Знання мають накопичуватися — а не випаровуватися.',
    compareBeforeLabel: 'Без пам\'яті',
    compareAfterLabel: 'Із Soleri',
    compareBefore: `<span class="dim">// Сесія 1</span>
<span class="warn">Ти:</span> Ми використовуємо Tailwind із семантичними токенами,
      ніколи — сирі hex. Базовий крок відступів — 4px.
<span class="warn">AI:</span>  Зрозуміло! Я цього дотримуватимуся.

<span class="dim">// Сесія 2 — наступного дня</span>
<span class="warn">Ти:</span> Чому ти знову використав #3B82F6?
<span class="warn">AI:</span>  Вибач, можеш нагадати мені
      твої домовленості щодо кольорів?

<span class="dim">// Сесія 47 — те саме питання, знову</span>`,
    compareAfter: `<span class="dim">// Сесія 1</span>
<span class="hl">Ти:</span> Ми використовуємо Tailwind із семантичними токенами.
<span class="hl">AI:</span>  Збережено у сховищі. Я це проконтролюю.

<span class="dim">// Сесія 47</span>
<span class="hl">Ти:</span> Переглянь цей компонент.
<span class="hl">AI:</span>  Знайдено 2 сирі hex-значення. У твоєму сховищі зазначено:
      лише семантичні токени. Виправляю.
      <span class="ok">✓ Шаблон застосовано зі сховища</span>
      <span class="ok">✓ Brain strength: 94% (12 сесій)</span>`,
    howTitle: 'Один рушій.<br/>Одне сховище.<br/>Жодної зайвої координації.',
    howText: '<strong>Сховище</strong> для знань, <strong>Brain</strong> для навчання, <strong>Memory</strong> для контексту. Один процес. Знання автоматично організуються, векторизуються й накопичуються.',
    engineTags: ['сховище', 'Brain', 'Memory'],
    features: [
      {
        title: 'Конфігурація як код',
        text: 'Одна команда генерує конфіг. Голос, домени, бекенди сховища — усе декларативно й під контролем версій.',
        code: `<span class="cmt"># agent.yaml (generated by create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">direct, technical, thorough</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastructure]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Підключувані пакети знань',
        text: 'npm-пакети, які можна підключити до будь-якого агента. Стартовий та спільнотний пакети безкоштовні.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">вбудовано</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">встановлено</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">встановлено</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">спільне сховище</span>`,
      },
      {
        title: 'Незалежний від транспорту та LLM',
        text: 'Чисте ядро TypeScript. Адаптери протоколів — окремі файли. Працює без API-ключів.',
        code: `<span class="key">engine/core/</span>        <span class="cmt"># zero protocol deps</span>
├── vault.ts
├── brain.ts
└── memory.ts
<span class="key">engine/transports/</span>  <span class="cmt"># swap without touching core</span>
├── <span class="ok">mcp.ts</span>         <span class="cmt"># ships now</span>
├── rest.ts        <span class="cmt"># dashboards, APIs</span>
└── lsp.ts         <span class="cmt"># VS Code, Cursor, Zed</span>`,
      },
      {
        title: 'Холодний старт, а не з нуля',
        text: 'Стартові знання — під час create. Сканування проєкту — під час першого запуску. Далі — керована фіксація.',
        code: `<span class="cmt">$ soleri create my-agent</span>
<span class="ok">✓</span> Installed starter knowledge  <span class="val">34 patterns</span>
<span class="ok">✓</span> Scanned project              <span class="val">React + TS</span>
<span class="ok">✓</span> Auto-captured                <span class="val">12 patterns</span>
<span class="ok">✓</span> Vault ready                  <span class="val">46 entries</span>

<span class="cmt"># After 3 sessions:</span>
<span class="warn">Brain:</span> You've fixed this import style 3×.
       <span class="val">Capture as pattern? [y/n]</span>`,
      },
    ],
    cardsTitle: 'Одне сховище. Багато доменів.',
    cards: [
      { title: 'Фронтенд', domain: 'Домен', cls: 'salvador', capabilities: ['Патерни React', 'Токени дизайну', 'Рев\'ю компонентів', 'Доступність'], ships: 'Запитай про кнопки — сховище спершу шукає тут.' },
      { title: 'Бекенд', domain: 'Домен', cls: 'gaudi', capabilities: ['Конвенції API', 'Схеми бази даних', 'Патерни автентифікації', 'Продуктивність'], ships: 'Запитай про запити чи дизайн API — сховище підтягує звідси.' },
      { title: 'Наскрізні', domain: 'Домен', cls: 'sentinel', capabilities: ['Робочі процеси Git', 'Код-рев\'ю', 'Стратегії тестування', 'Документація'], ships: 'Патерни, що охоплюють домени. Граф автоматично знаходить зв\'язки.' },
    ],
    terminalTitle: 'Термінал',
    terminalCode: `<span class="comment"># Встановлення та створення</span>
<span class="prompt">$</span> <span class="cmd">npm install</span> <span class="arg">-g soleri</span>
<span class="prompt">$</span> <span class="cmd">soleri create</span> <span class="arg">my-agent</span>

<span class="comment">  ✓ Створено конфіг агента</span>
<span class="comment">  ✓ Під'єднано Сховище (стартові знання: 34 патерни)</span>
<span class="comment">  ✓ Проскановано проєкт: React + TypeScript</span>
<span class="comment">  ✓ Автоматично зафіксовано 12 патернів кодової бази</span>
<span class="comment">  ✓ Сховище готове — 46 записів, векторизовано, з'єднано графом</span>

<span class="comment"># Додайте ще знань</span>
<span class="prompt">$</span> <span class="cmd">soleri packs</span> <span class="arg">install community/react-patterns</span>
<span class="prompt">$</span> <span class="cmd">soleri vault</span> <span class="arg">connect git@github.com:team/vault.git</span>`,
    archTitle: 'Багатошаровий, як живі системи',
    archSubtitle: 'Кожен шар зростає незалежно. Заміни транспорти, підключай знання, налаштовуй агента — рушій лишається тим самим.',
    layers: [
      { label: 'Агенти', text: 'Конфіг твого агента (<code>agent.yaml</code>): ідентичність, голос, прив\'язка доменів. Створи однією командою, налаштовуй будь-коли.' },
      { label: 'Домени', text: 'Підключувані домени знань. Рушій завантажує відповідні домени за структурою сховища твого агента.' },
      { label: 'Рушій', text: 'Один процес сервера MCP. Сховище (знання), Brain (навчання), Memory (контекст), Planning (робочі процеси). Твій агент працює на ньому. Оновлюй через <code>npm update</code>.' },
      { label: 'Транспорти', text: 'Адаптери протоколів ізольовані від ядра: <code>mcp.ts</code> постачається вже зараз, <code>rest.ts</code> і <code>lsp.ts</code> готові для VS Code, Cursor, Zed і кастомних дашбордів. Додати транспорт = один файл адаптера.' },
    ],
  },
  it: {
    heroTitle: 'Quello che <span class="accent-amber">insegni</span> resta. Quello che <span class="accent-teal">apprende</span> si accumula.',
    heroText: 'Memoria persistente. Conoscenza strutturata. Contesto che si mantiene in ogni sessione.',
    principleTitle: 'La conoscenza dovrebbe accumularsi, non evaporare.',
    compareBeforeLabel: 'Senza memoria',
    compareAfterLabel: 'Con Soleri',
    compareBefore: `<span class="dim">// Sessione 1</span>
<span class="warn">Tu:</span> Usiamo Tailwind con token semantici, mai esadecimale puro. Lo spazio è base 4px.
<span class="warn">AI:</span> Capito! Seguirò questo.

<span class="dim">// Sessione 2 — il giorno seguente</span>
<span class="warn">Tu:</span> Perché hai usato di nuovo #3B82F6?
<span class="warn">AI:</span> Scusa, puoi ricordarmi le tue convenzioni sui colori?

<span class="dim">// Sessione 47 — stessa domanda, ancora una volta</span>`,
    compareAfter: `<span class="dim">// Sessione 1</span>
<span class="hl">Tu:</span> Usiamo Tailwind con token semantici.
<span class="hl">AI:</span> Salvato nel Vault. D'ora in poi applicherò questa regola.

<span class="dim">// Sessione 47</span>
<span class="hl">Tu:</span> Rivedi questo componente.
<span class="hl">AI:</span> Ho trovato 2 valori esadecimali grezzi. Il Vault dice: solo token semantici. Correggo subito.
      <span class="ok">✓ Pattern applicato dal Vault</span>
      <span class="ok">✓ Brain strength: 94% (12 sessioni)</span>`,
    howTitle: 'Un motore.<br/>Un vault.<br/>Nessun sovraccarico di coordinamento.',
    howText: 'Un <strong>Vault</strong> per la conoscenza, un <strong>Cervello</strong> che apprende, una <strong>Memoria</strong> che persiste. Un unico processo. Dagli conoscenza — la organizza, la vettorializza e impara.',
    engineTags: ['Vault', 'Cervello', 'Memoria'],
    features: [
      {
        title: 'Configurazione come codice',
        text: 'Un comando genera la configurazione. Voce, domini, backend del vault — tutto dichiarativo, tutto sotto controllo di versione.',
        code: `<span class="cmt"># agent.yaml (generato da create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">diretto, tecnico, approfondito</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastruttura]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Pacchetti di conoscenza modulari',
        text: 'Pacchetti npm che inserisci in qualsiasi agente. I pacchetti Starter e Community sono gratuiti.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">integrato</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">installato</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">installato</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">vault condiviso</span>`,
      },
      {
        title: 'Indipendente da trasporti e LLM',
        text: 'Core in TypeScript puro. Gli adattatori di protocollo sono file separati. Cambia trasporti senza toccare il motore.',
        code: `<span class="key">engine/core/</span>        <span class="cmt"># zero dipendenze di protocollo</span>
├── vault.ts
├── brain.ts
└── memory.ts
<span class="key">engine/transports/</span>  <span class="cmt"># sostituisci senza toccare il core</span>
├── <span class="ok">mcp.ts</span>         <span class="cmt"># disponibile ora</span>
├── rest.ts        <span class="cmt"># dashboard, API</span>
└── lsp.ts         <span class="cmt"># VS Code, Cursor, Zed</span>`,
      },
      {
        title: 'Avvio a freddo, non una lavagna vuota',
        text: 'Conoscenza iniziale alla creazione. Scansione del progetto al primo avvio. Poi ti guida nell\'onboarding.',
        code: `<span class="cmt">$ soleri create my-agent</span>
<span class="ok">✓</span> Conoscenza iniziale installata  <span class="val">34 pattern</span>
<span class="ok">✓</span> Progetto scansionato              <span class="val">React + TS</span>
<span class="ok">✓</span> Acquisizione automatica                <span class="val">12 pattern</span>
<span class="ok">✓</span> Vault pronto                  <span class="val">46 voci</span>

<span class="cmt"># Dopo 3 sessioni:</span>
<span class="warn">Cervello:</span> Hai corretto questo stile di importazione 3 volte.
       <span class="val">Acquisire come pattern? [y/n]</span>`,
      },
    ],
    cardsTitle: 'Un vault. Molti domini.',
    cards: [
      { title: 'Frontend', domain: 'Dominio', cls: 'salvador', capabilities: ['Pattern React', 'Token di design', 'Revisione componenti', 'Accessibilità'], ships: 'Chiedi dei pulsanti — il vault cerca qui per primo.' },
      { title: 'Backend', domain: 'Dominio', cls: 'gaudi', capabilities: ['Convenzioni API', 'Schemi database', 'Pattern di autenticazione', 'Prestazioni'], ships: 'Chiedi di query o API design — il vault attinge da qui.' },
      { title: 'Trasversali', domain: 'Dominio', cls: 'sentinel', capabilities: ['Flussi di lavoro Git', 'Revisione del codice', 'Strategie di test', 'Documentazione'], ships: 'Pattern che attraversano i domini. Il grafo trova connessioni automaticamente.' },
    ],
    terminalTitle: 'Terminale',
    terminalCode: `<span class="comment"># Installa e crea</span>
<span class="prompt">$</span> <span class="cmd">npm install</span> <span class="arg">-g soleri</span>
<span class="prompt">$</span> <span class="cmd">soleri create</span> <span class="arg">my-agent</span>

<span class="comment">  ✓ Configurazione agente creata</span>
<span class="comment">  ✓ Vault connesso (conoscenza iniziale: 34 pattern)</span>
<span class="comment">  ✓ Progetto scansionato: React + TypeScript</span>
<span class="comment">  ✓ Acquisiti automaticamente 12 pattern dal codice</span>
<span class="comment">  ✓ Vault pronto — 46 voci, vettorializzate, connesse graficamente</span>

<span class="comment"># Alimentalo con più conoscenza</span>
<span class="prompt">$</span> <span class="cmd">soleri packs</span> <span class="arg">install community/react-patterns</span>
<span class="prompt">$</span> <span class="cmd">soleri vault</span> <span class="arg">connect git@github.com:team/vault.git</span>`,
    archTitle: 'Stratificato come un sistema vivente',
    archSubtitle: 'Ogni livello cresce indipendentemente. Sostituisci trasporti, inserisci conoscenza, personalizza il tuo agente — il motore rimane lo stesso.',
    layers: [
      { label: 'Agenti', text: 'La configurazione del tuo agente (<code>agent.yaml</code>): identità, voce, collegamento dei domini. Crea con un comando, personalizza in qualsiasi momento.' },
      { label: 'Domini', text: 'Domini di conoscenza modulari. Il motore carica i domini rilevanti in base alla struttura del vault del tuo agente.' },
      { label: 'Motore', text: 'Un unico processo MCP server. Vault (conoscenza), Cervello (apprendimento), Memoria (contesto), Pianificazione (flussi di lavoro). Il tuo agente ci gira sopra. Si aggiorna con <code>npm update</code>.' },
      { label: 'Trasporti', text: 'Adattatori di protocollo isolati dal core: <code>mcp.ts</code> disponibile ora, <code>rest.ts</code> e <code>lsp.ts</code> pronti per VS Code, Cursor, Zed e dashboard personalizzate. Aggiungi un trasporto = un file adattatore.' },
    ],
  },
};

interface HomeContent {
  heroTitle: string;
  heroText: string;
  principleTitle: string;
  compareBeforeLabel: string;
  compareAfterLabel: string;
  compareBefore: string;
  compareAfter: string;
  howTitle: string;
  howText: string;
  engineTags: string[];
  features: { title: string; text: string; code: string }[];
  cardsTitle: string;
  cards: { title: string; domain: string; cls: string; capabilities: string[]; ships: string }[];
  terminalTitle: string;
  terminalCode: string;
  archTitle: string;
  archSubtitle: string;
  layers: { label: string; text: string }[];
}
